apiVersion: apps/v1
kind: Deployment
metadata:
  name: project_4-deployment
  labels:
    app: project_4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project_4
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: deepak199812/project_4:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: project_4-service
spec:
  selector:
    app: project_4 
  type: LoadBalancer
  ports:
  - name: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
   
