apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    app: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: deepak199812/project:latest
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: project
spec:
  selector:
    app: project
  type: NodePort
  ports:
  - port: 80
    targetport: 80
    protocol: TCP
    nodePort: 31110
    
    
    
   
